name: Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  super-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Super Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JAVASCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
